### ISSUE TITLE
The published package does not contain the distribution files

### ISSUE THREAD

**Issue by zergeborg** [RawZ06/ngx-monaco-tree#1]
Hi @RawZ06 ! Thank you for this fantastic package! I really like it, and I could successfully make it working locally.

But I noticed that the published package is incorrect. I think what you would want to do is to run `ng build ngx-monaco-tree` which will create a dist folder, and then you can do:
```
cd dist/ngx-monaco-tree
npm publish
```

This will build the library in various different module formats suitable for different consumers, as well as a folder containing TypeScript definitions.

This article explains what I mean pretty clearly and briefly.
https://www.willtaylor.blog/complete-guide-to-angular-libraries/

**Comment by RawZ06** [comment]
Hi, thank you for your comment. I'm happy to learn that. 
This module was created to practice Angular framework and I didn't believe to have a feedback.
Yes I should to review this module to implements some new feature that I planned. 

Thank, for the next version, I will use this command to publish my module.

**Comment by RawZ06** [comment]
Hi, i fix it when i published a new version #2

**Comment by zergeborg** [comment]
Thank you for your fix. It's great!
