### ISSUE TITLE
How i can highlight effect?

### ISSUE THREAD

**Issue by nShieldSolo** [RawZ06/ngx-monaco-tree#6]
I want to have a highlight effect when selecting files, how can I do that?

Thank you for creating a great library.

**Comment by RawZ06** [comment]
Thank you for your interest in my library. Currently, I no longer have much time to maintain my library nor the motivation to do so. It was more of a project to learn Angular. Unfortunately, I do not have a feature to override the CSS. If you have the time, you can fork the project, make the update, and propose a PR.

Sorry for the late reply, I don't really read my GitHub much :)

**Comment by RawZ06** [comment]
Hello, I am getting back to you to announce that I have finally updated the project to Angular 17 with new features, and I have indeed added the highlight. 
Therefore, I invite you to download the now available version 17.1.0. 
Regarding Angular 18, I have not updated yet, as it is a version 18.0.x, so I am still waiting a bit. 
Thank you again for the attention you are giving to the project.

I can close this issue.
